### ISSUE TITLE
bug con el search

### ISSUE THREAD

**Issue by JavierLopezBlancoH** [CatalaHD/DiscordBot#4]
!search solo coge el primer elemento de la busqueda

**Comment by CatalaHD** [comment]
![image](https://user-images.githubusercontent.com/12767963/74203543-54bde280-4c70-11ea-8917-9977b4b48f58.png)

**Comment by CatalaHD** [comment]
![image](https://user-images.githubusercontent.com/12767963/74203629-93539d00-4c70-11ea-9a5f-df563ee65e50.png)

**Comment by CatalaHD** [comment]
Fixed in 51dc9815a2c9621ece734eb5350c1945b3f54062
