### ISSUE TITLE
!search no borra correctamente los mensajes

### ISSUE THREAD

**Issue by JavierLopezBlancoH** [CatalaHD/DiscordBot#5]
Reproduccion del bug:
1.
![image](https://user-images.githubusercontent.com/49500332/74204513-cc414100-4c73-11ea-8dff-8b163acc1fb6.png)
2.
![image](https://user-images.githubusercontent.com/49500332/74204529-de22e400-4c73-11ea-8e1c-e9a62bac86fc.png)
"Se puede ver que no borra el mensaje de busqueda correctamente y no envia el mensaje con el video a reproducir".
El bot pone correctamente la musica en la cola y se reproduce correctamente.
Buen bot

**Comment by CatalaHD** [comment]
Parece un error casual que no pasa casi nunca y no se puede arreglar, por ahora lo dejamos cerrado y si vuelve a ocurrir lo volvemos a abrir
